name: CI/CD for two tier
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure-AWS-Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: us-east-1

      - name: login to ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag
        id: build-image
        env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           ECR_REPOSITORY: two-tier
           IMAGE_TAG: latest
        run: |
           docker build -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} .
           docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

      - name: Update Kubeconfig
        run: |
            aws eks --region us-east-1 update-kubeconfig --name test

      - name: Run Kubernetes
        run: |
            kubectl apply -f mysql-configmap.yml
            kubectl apply -f mysql-deployment.yml
            kubectl apply -f mysql-secrets.yml
            kubectl apply -f mysql-svc.yml
            kubectl apply -f two-tier-app-deployment.yml
            kubectl apply -f two-tier-app-svc.yml
      
      
